include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    lib/models/**
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    avoid_classes_with_only_static_members: false
    avoid_dynamic_calls: true
    avoid_redundant_argument_values: false
    literal_only_boolean_expressions: true
    omit_local_variable_types: true
    only_throw_errors: true
    prefer_single_quotes: true
    unawaited_futures: true
    unnecessary_constructor_name: true
    unnecessary_lambdas: true
    unnecessary_late: true
    use_key_in_widget_constructors: true
