targets:
  $default:
    builders:
      artemis:
        options:
          generate_helpers: true
          schema_mapping:
            - schema: lib/api/schema.graphql
              output: lib/api/api.graphql.dart
              fragments_glob: lib/api/fragments/**.graphql
              queries_glob: lib/api/queries/**.graphql
              naming_scheme: pathedWithTypes
              type_name_field: __typename
          custom_parser_import: 'package:climate_platform_ui/api/custom_scalars.dart'
          scalar_mapping:
            - graphql_type: AWSDateTime
              dart_type: DateTime
