name: climate_platform_ui
description: Demo

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: '>=3.3.9'

assets:
  - .env.local

dependencies:
  artemis: ^7.9.0-beta
  collection: ^1.16.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.5+1
  get_it: ^7.2.0
  go_router: ^5.2.4
  google_fonts: ^3.0.1
  gql: ^0.13.1
  gql_dedupe_link: ^2.0.3-alpha+1659715356233
  gql_http_link: ^0.4.3-alpha+1659715356170
  gql_link: ^0.4.3-alpha+1659715356132
  hooks_riverpod: ^2.1.1
  http: ^0.13.5
  infinite_scroll_pagination: ^3.2.0
  json_annotation: ^4.7.0
  meta: ^1.8.0
  reactive_forms: ^14.1.0
  riverpod_annotation: ^1.1.1

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  lint: ^2.0.1
  riverpod_generator:

flutter:
  uses-material-design: true
  assets:
    - .env.local
