name: climate_platform_ui
description: Demo

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  amplify_api: ^0.6.0
  amplify_auth_cognito: ^0.6.0
  amplify_flutter: ^0.6.0
  artemis: ^7.7.0-beta
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  gql: ^0.13.1
  json_annotation: ^4.5.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  lint: ^1.8.2

flutter:
  uses-material-design: true