name: climate
description: Demo

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.7.0'

assets:
  - .env.local

dependencies:
  artemis:
  async:
  collection:
  equatable:
  flutter:
    sdk: flutter
  flutter_dotenv:
  flutter_hooks:
  flutter_markdown:
  freezed_annotation:
  get_it:
  go_router:
  google_fonts:
  gql:
  gql_dedupe_link:
  gql_exec:
  gql_http_link:
  gql_link:
  gql_websocket_link:
  hooks_riverpod:
  http:
  infinite_scroll_pagination:
  json_annotation:
  meta:
  reactive_forms:
  riverpod_annotation:
  uuid:
  web_socket_channel:

dependency_overrides:
  # leaving out version causes upgrade to use the newest version
  # safe to do so, assuming libs don't cause breaking changes
  collection:
  file:
  http:
  path:

dev_dependencies:
  build_runner:
  file:
  flutter_test:
    sdk: flutter
  freezed:
  golden_toolkit:
  json_serializable:
  lint:
  mockito:
  path:
  platform:
  riverpod_generator:

flutter:
  uses-material-design: true
  assets:
    - .env.local
    - assets/google_fonts/
