name: climate_platform_ui
description: Demo

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

assets:
  - .env.local

dependencies:
  artemis: ^7.11.0-beta.1
  async: ^2.10.0
  collection: ^1.17.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.0.1
  google_fonts: ^4.0.1
  gql: ^0.14.0
  gql_dedupe_link: ^2.0.3
  gql_exec: ^0.4.1
  gql_http_link: ^0.4.4+1
  gql_link: ^0.5.0
  gql_websocket_link: ^0.3.4
  hooks_riverpod: ^2.1.1
  http: ^0.13.5
  infinite_scroll_pagination: ^3.2.0
  json_annotation: ^4.7.0
  meta: ^1.8.0
  reactive_forms: ^14.1.0
  riverpod_annotation: ^1.1.1
  uuid: ^3.0.7
  web_socket_channel: ^2.3.0

dev_dependencies:
  build_runner:
  file:
  flutter_test:
    sdk: flutter
  freezed:
  golden_toolkit:
  json_serializable:
  lint:
  mockito:
  path:
  platform:
  riverpod_generator:

flutter:
  uses-material-design: true
  assets:
    - .env.local
    - assets/google_fonts/
