name: climate
description: Demo

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.7.0'

assets:
  - .env.local

dependencies:
  amplify_auth_cognito: 1.6.0
  amplify_authenticator: 1.5.0
  amplify_flutter: 1.6.0
  artemis: 7.13.1
  async: 2.11.0
  collection: 1.18.0
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: 5.1.0
  flutter_hooks: 0.20.3
  flutter_markdown: 0.6.18
  freezed_annotation: 2.4.1
  get_it: 7.6.4
  go_router: 11.1.4
  google_fonts: 6.1.0
  gql: 1.0.0
  gql_exec: 1.0.0
  gql_http_link: 1.0.1
  gql_link: 1.0.0
  gql_websocket_link: 1.1.0
  hooks_riverpod: 2.4.5
  http: 1.1.0
  infinite_scroll_pagination: 4.0.0
  json_annotation: 4.8.1
  meta: 1.9.1
  reactive_forms: 16.1.1
  riverpod_annotation: 2.3.0
  uuid: 3.0.7
  web_socket_channel: 2.4.0

dependency_overrides:
  # leaving out version causes upgrade to use the newest version
  # safe to do so, assuming libs don't cause breaking changes
  collection:
  file:
  gql: # artemis is not updated yet
  gql_exec: # artemis is not updated yet
  gql_http_link: # artemis is not updated yet
  gql_link: # artemis is not updated yet
  http:
  path:

dev_dependencies:
  build_runner: 2.4.6
  file: 7.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.4.5
  golden_toolkit: 0.15.0
  json_serializable: 6.7.1
  lint: 2.1.2
  mockito: 5.4.2
  path: 1.8.3
  platform: 3.1.3
  riverpod_generator: 2.3.5

flutter:
  uses-material-design: true
  assets:
    - .env.local
    - assets/google_fonts/
