# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins

require 'yaml'

default_platform(:ios)

key_id = ENV["APP_STORE_CONNECT_API_KEY_ID"]
app_store_connect_api_key(
  key_id: key_id,
  issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
  key_filepath: File.expand_path("~/.private_keys/AuthKey_#{key_id}.p8")
)

platform :ios do
  desc "Requests, calculates and sets the next build version in the pubspec.yaml."
  lane :set_next_version_in_pubspec do |options|
    # TODO coordinate build number and version with android rollout
    latest_build_number = latest_testflight_build_number(initial_build_number: 0)
    # TODO allow increment (major, minor, patch) of version via options
    latest_version = lane_context[SharedValues::LATEST_TESTFLIGHT_VERSION]
    next_combined_version = "#{latest_version}+#{latest_build_number + 1}"
    UI.success("Next combined build version is #{next_combined_version}.")

    pubspec_path = "../../pubspec.yaml"
    pubspec = YAML.load_file(pubspec_path)
    pubspec['version'] = next_combined_version
    File.open(pubspec_path, 'w') { |file| YAML.dump(pubspec, file) }
  end
end
