name: "Deployment"

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - .fvm
      - android
      - assets
      - ios
      - lib
      - web
      - .env
      - pubspec.lock
      - pubspec.yaml
    branches:
      - main

concurrency:
  group: "deployment"
  cancel-in-progress: false

jobs:
  test:
    if: ${{ github.actor != 'renovate[bot]' }} # don't deploy on renovate merge
    name: "Test"
    uses: ./.github/workflows/test.yml
    secrets: inherit
  deploy-web:
    needs: test
    name: "Deploy Web"
    uses: ./.github/workflows/deploy-web.yml
    secrets: inherit
  deploy-ios:
    needs: test
    name: "Deploy iOS"
    uses: ./.github/workflows/deploy-ios.yml
    secrets: inherit
  deploy-android:
    needs: test
    name: "Deploy Android"
    uses: ./.github/workflows/deploy-android.yml
    secrets: inherit
