name: "Deploy iOS"

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: "Version to be used in pubspec.yaml"
        type: string
        required: true
  workflow_call:
    inputs:
      next_version:
        description: "Version to be used in pubspec.yaml"
        type: string
        required: true
    secrets:
      APP_SYNC_API_KEY:
        required: true
      APP_STORE_CONNECT_APPLE_ID:
        required: true
      APP_STORE_CONNECT_ISSUER_ID:
        required: true
      APP_STORE_CONNECT_API_KEY_ID:
        required: true
      APP_STORE_CONNECT_API_KEY_FILE:
        required: true
      APP_STORE_DISTRIBUTION_CERT_ID:
        required: true
      APP_STORE_DISTRIBUTION_CERT_KEY_FILE:
        required: true
      SECRET_SETTING_TOKEN:
        required: true

jobs:
  build:
    name: "Build"
    runs-on: macos-latest
    env:
      APP_STORE_CONNECT_APPLE_ID: ${{ secrets.APP_STORE_CONNECT_APPLE_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
    steps:
      - name: "Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: "Setup empty .env.local"
        run: sed 's/APP_SYNC_API_KEY.*/APP_SYNC_API_KEY="${{ secrets.APP_SYNC_API_KEY }}"/' .env > .env.local
      - name: "Determine Flutter Version"
        id: flutter-version
        run: echo "FLUTTER_VERSION=$(jq -r ".flutterSdkVersion" .fvm/fvm_config.json)" >> $GITHUB_OUTPUT
      - name: "Setup Flutter"
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: ${{ steps.flutter-version.outputs.FLUTTER_VERSION }}
          cache: true
      - name: "Setup Ruby"
        uses: ruby/setup-ruby@5cfe23c062c0aac352e765b1b7cc12ea5255ccc4 # v1.156.0
        with:
          # using .ruby-version
          # installing gems automatically
          bundler-cache: true # requires BUNDLE_GEMFILE
      - name: "Setup Xcode"
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest-stable
      - name: "Setup API key"
        env:
          # 1. `base64 -i AuthKey_<...>.p8 -o AuthKey_<...>.base64`
          # 2. `pbcopy < AuthKey_<...>.base64` and paste without a newline
          APP_STORE_CONNECT_API_KEY_FILE: ${{ secrets.APP_STORE_CONNECT_API_KEY_FILE }}
        run: |
          mkdir ~/.private_keys
          echo $APP_STORE_CONNECT_API_KEY_FILE | base64 --decode > ~/.private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}.p8
      - name: "Set build version"
        run: yq -i '.version = "${{ inputs.next_version }}"' pubspec.yaml
      - name: "Pre-Build via Flutter"
        run: flutter build ios --no-codesign --release
      - name: "Setup distribution certificate key"
        env:
          # automatically generated by previous runs via fastlane
          APP_STORE_DISTRIBUTION_CERT_KEY_FILE: ${{ secrets.APP_STORE_DISTRIBUTION_CERT_KEY_FILE }}
        run: |
          echo $APP_STORE_DISTRIBUTION_CERT_KEY_FILE | base64 --decode > ${{ secrets.APP_STORE_DISTRIBUTION_CERT_ID }}.p12
      - name: "Build & Sign via Fastlane"
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          SECRET_SETTING_TOKEN: ${{ secrets.SECRET_SETTING_TOKEN }}
        run: bundle exec fastlane ios_build
      - name: "Upload ipa artifact"
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ios-ipa
          path: Runner.ipa
      - name: "Upload dSYM artifact"
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ios-dsym
          path: Runner.app.dSYM.zip
  deploy:
    needs: build
    name: "Deploy"
    runs-on: macos-latest
    environment:
      name: testflight
      url: https://testflight.apple.com/join/VNxf4EKg
    env:
      APP_STORE_CONNECT_APPLE_ID: ${{ secrets.APP_STORE_CONNECT_APPLE_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
    steps:
      - name: "Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: "Setup Ruby"
        uses: ruby/setup-ruby@5cfe23c062c0aac352e765b1b7cc12ea5255ccc4 # v1.156.0
        with:
          # using .ruby-version
          # installing gems automatically
          bundler-cache: true # requires BUNDLE_GEMFILE
      - name: "Setup Xcode"
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest-stable
      - name: "Setup API key"
        env:
          # 1. `base64 -i AuthKey_<...>.p8 -o AuthKey_<...>.base64`
          # 2. `pbcopy < AuthKey_<...>.base64` and paste without a newline
          APP_STORE_CONNECT_API_KEY_FILE: ${{ secrets.APP_STORE_CONNECT_API_KEY_FILE }}
        run: |
          mkdir ~/.private_keys
          echo $APP_STORE_CONNECT_API_KEY_FILE | base64 --decode > ~/.private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}.p8
      - name: "Download ipa artifact"
        uses: actions/download-artifact@v3.0.2
        with:
          name: ios-ipa
      - name: "Deploy via Fastlane"
        run: bundle exec fastlane ios_deploy
