name: "Deploy Android"

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APP_SYNC_API_KEY:
        required: true

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/android/Gemfile
    steps:
      - name: "Checkout"
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: "Setup Empty .env.local"
        run: sed 's/APP_SYNC_API_KEY.*/APP_SYNC_API_KEY="${{ secrets.APP_SYNC_API_KEY }}"/' .env > .env.local
      - name: "Determine Flutter Version"
        id: flutter-version
        run: echo "FLUTTER_VERSION=$(jq -r ".flutterSdkVersion" .fvm/fvm_config.json)" >> $GITHUB_OUTPUT
      - name: "Setup Flutter"
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: ${{ steps.flutter-version.outputs.FLUTTER_VERSION }}
          cache: true
      - name: "Setup Ruby"
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          # using .ruby-version
          # installing gems automatically
          bundler-cache: true # requires BUNDLE_GEMFILE

# TODO
#      - name: "Setup next version in pubspec.yaml"
#        working-directory: android
#        run: bundle exec fastlane set_next_version_in_pubspec

#      - name: "Upload ipa artifact"
#        uses: actions/upload-artifact@v3.1.3
#        with:
#          name: TODO
#          path: TODO
  deploy:
    needs: build
    name: "Deploy"
    runs-on: ubuntu-latest
#    environment:
#      name: TODO
#      url: TODO
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/android/Gemfile
    steps:
      - name: "Checkout"
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: "Setup Ruby"
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          # using .ruby-version
          # installing gems automatically
          bundler-cache: true # requires BUNDLE_GEMFILE

#      - name: "Download ipa artifact"
#        uses: actions/download-artifact@v3.0.2
#        with:
#          name: TODO
#          path: TODO
#      - name: "Deploy via Fastlane"
#        working-directory: ios
#        run: bundle exec fastlane deploy
