name: "Deployment"

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

concurrency:
  group: "deployment"
  cancel-in-progress: false

jobs:
  test:
    name: "Test"
    uses: ./.github/workflows/test.yml
    secrets: inherit
  deploy-web:
    needs: test
    name: "Deploy Web"
    uses: ./.github/workflows/deploy-web.yml
    secrets: inherit
  deploy-ios:
    needs: test
    name: "Deploy iOS"
    uses: ./.github/workflows/deploy-ios.yml
    secrets: inherit
