on: push

name: "Deploy All"

jobs:
  test-code:
    name: "Test code"
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup Empty .env.local"
        run: cp .env .env.local
      - name: "Determine Flutter Version"
        id: flutter-version
        run: echo "FLUTTER_VERSION=$(jq -r ".flutterSdkVersion" .fvm/fvm_config.json)" >> $GITHUB_OUTPUT
      - name: "Install Flutter"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.flutter-version.outputs.FLUTTER_VERSION }}
          cache: true
      - name: "Install Dependencies"
        run: flutter pub get
      - name: "Run Tests"
        run: flutter test --coverage
      - name: "Upload Coverage Report to Codecov"
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true
  submit-ios:
    name: "Submit iOS"
    runs-on: macos-latest
    timeout-minutes: 60
    needs:
      - test-code
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup Xcode"
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: "Determine Flutter Version"
        id: flutter-version
        run: echo "FLUTTER_VERSION=$(jq -r ".flutterSdkVersion" .fvm/fvm_config.json)" >> $GITHUB_OUTPUT
      - name: "Install Flutter"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.flutter-version.outputs.FLUTTER_VERSION }}
          cache: true

