name: "Deployment"

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths: # don't deploy on renovate merge, so pubspec & fvm files are not included
      - "android/**"
      - "assets/**"
      - "ios/**"
      - "lib/**"
      - "web/**"
      - .env
    branches:
      - main

concurrency:
  group: "deployment"
  cancel-in-progress: false

jobs:
  test:
    name: "Test"
    uses: ./.github/workflows/test.yml
    secrets: inherit
  deploy-web:
    needs: test
    name: "Deploy Web"
    uses: ./.github/workflows/deploy-web.yml
    secrets: inherit
    with:
      next_version: ${{ needs.test.outputs.next_version }}
  deploy-ios:
    needs: test
    name: "Deploy iOS"
    uses: ./.github/workflows/deploy-ios.yml
    secrets: inherit
    with:
      next_version: ${{ needs.test.outputs.next_version }}
  deploy-android:
    needs: test
    name: "Deploy Android"
    uses: ./.github/workflows/deploy-android.yml
    secrets: inherit
    with:
      next_version: ${{ needs.test.outputs.next_version }}
