name: Renovate
on:
  push:
  workflow_dispatch:
#  schedule:
#    - cron: '*/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.3
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}

