name: "Renovate"

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/renovate.json'
  pull_request:
    types: [ edited ]
  issues:
    types: [ edited ]
  issue_comment:
    types: [ edited ]
  schedule:
    - cron: '0 2 * * *'
jobs:
  run:
    name: "Run"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.3
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}

