name: "Test"

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APP_STORE_CONNECT_APPLE_ID:
        required: true
      APP_STORE_CONNECT_ISSUER_ID:
        required: true
      APP_STORE_CONNECT_API_KEY_ID:
        required: true
      APP_STORE_CONNECT_API_KEY_FILE:
        required: true
      APP_STORE_DISTRIBUTION_CERT_ID:
        required: true
      APP_STORE_DISTRIBUTION_CERT_KEY_FILE:
        required: true
      CODECOV_TOKEN:
        required: true
      SECRET_SETTING_TOKEN:
        required: true
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test-flutter:
    name: "Flutter"
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: "Checkout"
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: "Setup Empty .env.local"
        run: cp .env .env.local
      - name: "Determine Flutter Version"
        id: flutter-version
        run: echo "FLUTTER_VERSION=$(jq -r ".flutterSdkVersion" .fvm/fvm_config.json)" >> $GITHUB_OUTPUT
      - name: "Install Flutter"
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: ${{ steps.flutter-version.outputs.FLUTTER_VERSION }}
          cache: true
      - name: "Pub Get"
        run: flutter pub get # so pub get doesn't clutter flutter test output
      - name: "Run Tests"
        id: run-tests
        run: flutter test --coverage --suppress-analytics --machine | tee test-report.json # --suppress-analytics needed to have a valid json
      - name: "Add test results to status check"
        uses: phoenix-actions/test-reporting@v12
        if: always() && (steps.run-tests.outcome == 'failure' || steps.run-tests.outcome == 'success')
        with:
          reporter: dart-json
          name: "Test Results: Flutter"
          path: test-report.json
      - name: "Upload Coverage Report to Codecov"
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true
  test-fastlane:
    name: "Fastlane"
    runs-on: macos-latest
    env:
      APP_STORE_CONNECT_APPLE_ID: ${{ secrets.APP_STORE_CONNECT_APPLE_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
    steps:
      - name: "Checkout"
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: "Setup Ruby"
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          # using .ruby-version
          # installing gems automatically
          bundler-cache: true # requires BUNDLE_GEMFILE
      - name: "Setup Xcode"
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: latest-stable
      - name: "Setup App Store Connect API key"
        env:
          # 1. `base64 -i AuthKey_<...>.p8 -o AuthKey_<...>.base64`
          # 2. `pbcopy < AuthKey_<...>.base64` and paste without a newline
          APP_STORE_CONNECT_API_KEY_FILE: ${{ secrets.APP_STORE_CONNECT_API_KEY_FILE }}
        run: |
          mkdir ~/.private_keys
          echo $APP_STORE_CONNECT_API_KEY_FILE | base64 --decode > ~/.private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}.p8
      - name: "Setup Google Play Console API key"
        env:
          # 1. `base64 -i play-store-credentials.json -o play-store-credentials.base64`
          # 2. `pbcopy < play-store-credentials.base64` and paste without a newline
          GOOGLE_PLAY_CONSOLE_API_KEY_FILE: ${{ secrets.GOOGLE_PLAY_CONSOLE_API_KEY_FILE }}
        run: |
          echo $GOOGLE_PLAY_CONSOLE_API_KEY_FILE | base64 --decode > ./android/play-store-credentials.json
      - name: "Check App & Play Store access by calculating next version"
        run: bundle exec fastlane set_next_version
  test-fastlane-ios:
    name: "Fastlane for iOS"
    runs-on: macos-latest
    env:
      APP_STORE_CONNECT_APPLE_ID: ${{ secrets.APP_STORE_CONNECT_APPLE_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      BUNDLE_GEMFILE: ${{ github.workspace }}/ios/Gemfile
    steps:
      - name: "Checkout"
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: "Setup Ruby"
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          # using .ruby-version
          # installing gems automatically
          bundler-cache: true # requires BUNDLE_GEMFILE
      - name: "Setup Xcode"
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: latest-stable
      - name: "Setup API key"
        env:
          # 1. `base64 -i AuthKey_<...>.p8 -o AuthKey_<...>.base64`
          # 2. `pbcopy < AuthKey_<...>.base64` and paste without a newline
          APP_STORE_CONNECT_API_KEY_FILE: ${{ secrets.APP_STORE_CONNECT_API_KEY_FILE }}
        run: |
          mkdir ~/.private_keys
          echo $APP_STORE_CONNECT_API_KEY_FILE | base64 --decode > ~/.private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}.p8
      - name: "Check whether App Store access works"
        working-directory: ios
        run: bundle exec fastlane set_next_version_in_pubspec
      - name: "Setup distribution certificate key"
        working-directory: ios
        env:
          # automatically generated by previous runs via fastlane
          APP_STORE_DISTRIBUTION_CERT_KEY_FILE: ${{ secrets.APP_STORE_DISTRIBUTION_CERT_KEY_FILE }}
        run: |
          echo $APP_STORE_DISTRIBUTION_CERT_KEY_FILE | base64 --decode > ${{ secrets.APP_STORE_DISTRIBUTION_CERT_ID }}.p12
      - name: "Check certificates by ensuring validity"
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          SECRET_SETTING_TOKEN: ${{ secrets.SECRET_SETTING_TOKEN }}
        working-directory: ios
        run: bundle exec fastlane ensure_certificate
  test-fastlane-android:
    name: "Fastlane for Android"
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/android/Gemfile
    steps:
      - name: "Checkout"
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: "Setup Ruby"
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          # using .ruby-version
          # installing gems automatically
          bundler-cache: true # requires BUNDLE_GEMFILE
      - name: "Setup API key"
        env:
          # 1. `base64 -i play-store-credentials.json -o play-store-credentials.base64`
          # 2. `pbcopy < play-store-credentials.base64` and paste without a newline
          GOOGLE_PLAY_CONSOLE_API_KEY_FILE: ${{ secrets.GOOGLE_PLAY_CONSOLE_API_KEY_FILE }}
        run: |
          echo $GOOGLE_PLAY_CONSOLE_API_KEY_FILE | base64 --decode > ./android/play-store-credentials.json
      - name: "Check whether Play Store access works"
        working-directory: android
        run: bundle exec fastlane ensure_correctness
